# 1. Define a variable miles and write an assignment statement that defines a variable feet whose value is the number of feet in miles miles. 
miles = 
# 2. Define three variables: hours , minutes and seconds , write an assignment statement that updates the variable total_seconds to have a value corresponding to the total number of seconds for hours hours, minutes minutes and seconds seconds.
# 3. Define variables width and height that are the lengths of the sides of a rectangle, write an assignment statement that defines a variable perimeter whose value is the perimeter of the rectangle in centimeters.
# 4. Define the variables width and height that are the lengths of the sides of a rectangle, write an assignment statement that defines a variable area whose value is the area of the rectangle in square centimeters.
# 5. Define the constant π as 3.14159 and the variable radius corresponding to the radius of a circle in centimeters, write an assignment statement that defines a variable circumference whose value is the circumference of a circle with radius radius in centimeters.
# 6. Define the constant π as 3.14159 and the variable radius corresponding to the radius of a circle in centimeters, write an assignment statement that defines a variable area whose value is the area of a circle with radius radius in square centimeters.
# 7. Define the variables present_value , annual_rate and years , write an assignment statement that define a variable future_value whose value is present_value dollars invested at annual_rate , percent , interest , compounded annually for years years.
# 8. Define the variables first_name and last_name , write an assignment statement that defines the variable name_tag whose value is the string “My name is % %.” where the percents should be replaced by first_name and last_name.
# 9. Define the variables name (a string) and age (a number), write an assignment statement that defines a variable statement whose value is the string “% is % years old.” where the percents should be replaced by name and the string form of age.
# 10. Given the variables x 0 , y 0 , x 1 , and y 1 , write an assignment statement that defines a variable distance whose values is the distance between the points ( x 0 ,y 0 ) and (x 1 ,y 1 ).
# 11. Challenge: Heron’s formula states the area of a triangle is p p(p − a)(p − b)(p − c) 1 where a , b and c are the lengths of the sides of the triangle and p = 1 2 ( a + b + c ) is the semi-perimeter of the triangle. Given the variables x 0 , y 0 , x 1 , y 1 , x 2 , and y 2 , write a Python program that computes a variable area whose value is the area of the triangle with vertices (x 0 ,y 0 ), (x 1 ,y 1 ) and (x 2 ,y 2 )